# Generated by Django 4.1.5 on 2023-01-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_pelicula', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('pais_de_origen', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_estreno', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proximos_estrenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_pelicula', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('pais_de_origen', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_pelicula', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('pais_de_origen', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('plataforma', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion_serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_pelicula', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=500)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critica_cine.series')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion_cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_pelicula', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=500)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='critica_cine.peliculas')),
            ],
        ),
    ]
